from supabase import create_client

SUPABASE_URL = "https://iqfhgjrzkyscaixddkbj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZmhnanJ6a3lzY2FpeGRka2JqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjM3NTM2OSwiZXhwIjoyMDg3OTUxMzY5fQ.llc7AHeRsfEVHVSelNjGTcp7dGoLWvLWa1vZCj2nxRU"

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)